site_name: iter8
site_description: Lazy iterator objects for Lua 5.4+
site_url: https://jparoz.github.io/iter8/
repo_url: https://github.com/jparoz/iter8
repo_name: jparoz/iter8

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details

nav:
  - Home: index.md
  - API Reference: api.md
